"""empty message

Revision ID: 228a21c6e90e
Revises: cd4b7ffc7e93
Create Date: 2020-08-25 08:40:04.314831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '228a21c6e90e'
down_revision = 'cd4b7ffc7e93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
