"""empty message

Revision ID: 624f4b1aa0fb
Revises: de7d2f7b6c71
Create Date: 2020-08-12 21:29:18.393154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '624f4b1aa0fb'
down_revision = 'de7d2f7b6c71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'meals', 'categories', ['category_id'], ['id'])
    op.add_column('orders', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'user_id')
    op.drop_constraint(None, 'meals', type_='foreignkey')
    op.drop_column('meals', 'category_id')
    # ### end Alembic commands ###
