"""empty message

Revision ID: 812d2549e8a5
Revises: 228a21c6e90e
Create Date: 2020-08-27 09:51:46.729854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812d2549e8a5'
down_revision = '228a21c6e90e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders_meals', sa.Column('qnt', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders_meals', 'qnt')
    # ### end Alembic commands ###
