"""empty message

Revision ID: cd4b7ffc7e93
Revises: 624f4b1aa0fb
Create Date: 2020-08-18 21:49:00.573540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd4b7ffc7e93'
down_revision = '624f4b1aa0fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=1000), nullable=False))
    op.alter_column('users', 'address',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'address',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
